name: 东东萌宠

on:
  workflow_dispatch:
    push:
        branches:
            - main
    schedule:
        - cron: '15 6 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: '运行 【东东萌宠】'
              run: npm install
            - run: node jd_pet.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
